apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: flask-app
  name: flask-app
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - image: 'cremerfc/flask-app:${trigger["buildInfo"]["number"]}'
          name: flask-app
          ports:
            - containerPort: 5000
