apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service bg-flask-app-service"]'
  labels:
    app: bg-flask-app
  name: bg-flask-app
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bg-flask-app
  template:
    metadata:
      labels:
        app: bg-flask-app
    spec:
      containers:
        - image: 'cremerfc/flask-app:${trigger["buildInfo"]["number"]}'
          name: flask-app
          ports:
            - containerPort: 5000
